### ISSUE TITLE
gNOI Packet Based Link Qualification Pacing Question

### ISSUE THREAD

**Issue by aredmon8551** [openconfig/gnoi#102]
General question - is there any guidance on the pacing/time spacing to use when transmitting packets (beyond per second granularity)?
https://github.com/openconfig/gnoi/blob/c3391aacaa1b33c4dfc4052d70938fb083798e3a/packet_link_qualification/packet_link_qualification.proto#L149

**Comment by marcushines** [comment]
it expected to just be a constant flow that averages to the packet rate
