### ISSUE TITLE
compile_protos.sh: os and factory_reset not present

### ISSUE THREAD

**Issue by kevinriviere** [openconfig/gnoi#33]
Commit [`70d7ea1`](https://github.com/openconfig/gnoi/commit/70d7ea1963de5455fe5ae3007435c97c43401338) added [`os.proto`](https://github.com/openconfig/gnoi/blob/master/os/os.proto) and commit [`e586e41`](https://github.com/openconfig/gnoi/commit/e586e41e1e392e832eab31197b4020eb525e10a6) added [`reset.proto`](https://github.com/openconfig/gnoi/blob/master/factory_reset/reset.proto), but the packages `os` and `factory_reset` were not added to [`compile_protos.sh`](https://github.com/openconfig/gnoi/blob/master/compile_protos.sh). Is that expected?

**Comment by samribeiro** [comment]
#34

**Comment by marcushines** [comment]
Fixed
