### ISSUE TITLE
Inconsistent specification of Ping count of 0

### ISSUE THREAD

**Issue by greg-dennis** [openconfig/gnoi#60]
In the doc of the Ping RPC is says "If a packet count is not explicitly provided, 5 is used":
https://github.com/openconfig/gnoi/blob/master/system/system.proto#L39

In the doc of PingRequest it says "A count of 0 defaults to a vendor specified value, typically 5."
https://github.com/openconfig/gnoi/blob/master/system/system.proto#L172

So must a count of zero use 5 or is it really left up to the vendor?

Regardless, I recommend removing any mention of the count from the RPC itself, so that the code only contains one source of truth for what a zero count means.

**Comment by marcushines** [comment]
Going to remove the line in the rpc spec
