### ISSUE TITLE
healthz.proto response should be streaming type

### ISSUE THREAD

**Issue by amanand** [openconfig/gnoi#64]
In order to export core files or large outputs like "show tech-support" as part of the RPC response, shouldn't the rpc be server streaming type?
https://github.com/openconfig/gnoi/blob/7dd3a95a4f1ee589048ac8ebe6ac84c154c152df/healthz/healthz.proto#L43

**Comment by marcushines** [comment]
Addressed in the streaming healthz PR https://github.com/openconfig/gnoi/pull/79
