### ISSUE TITLE
file timestamp as decimal or octal?

### ISSUE THREAD

**Issue by hellt** [openconfig/gnoi#77]
Hi all,
in gnoi file permissions are conveyed via uint32 type like shown here for example

https://github.com/openconfig/gnoi/blob/master/file/file.proto#L146

What proto doesn't clarify is that what value should be conveyed in this uint 32 field, should it be 

* a decimal representation of a unix permisson value
* or an octal value encoded as a decimal?

For example, for a unix permission value of `777`, should the value be `777` or `511`, where `511` is `o777` converted to decimal?

**Comment by hellt** [comment]
👋 @robshakir @marcushines 
do you guys have a view on what is required?

**Comment by marcushines** [comment]
it was just use the int value to to hold the actual octal representation i.e.
i.e. no base conversion should be necessary to read / write the value

755 stays 755 
4755 stays 4755 and so on

**Comment by hellt** [comment]
thanks for clarifications!
