### ISSUE TITLE
clarification on `file.stat` behavior for directories

### ISSUE THREAD

**Issue by hellt** [openconfig/gnoi#92]
Hi all,
what is expected from a target when [File.Stat RPC](https://github.com/openconfig/gnoi/blob/6bddacd72ef8aa06304b887df414a43c8e63ff27/file/file.proto#L128-LL155) is used with a path that points to a directory with nested directories?

Should the target recursively provide stat information or should it only consider files/directories listed by the specified path without doing recursive lookups?

**Comment by marcushines** [comment]
I don't believe recursion is expected only a list of all objects at the provided path
